# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-100-Master.xdc

# Block Designs: bd/ts_pt100/ts_pt100.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100 || ORIG_REF_NAME==ts_pt100}]

# IP: bd/ts_pt100/ip/ts_pt100_alarm_HT_v_0_0/ts_pt100_alarm_HT_v_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100_alarm_HT_v_0_0 || ORIG_REF_NAME==ts_pt100_alarm_HT_v_0_0}]

# IP: bd/ts_pt100/ip/ts_pt100_AD1_driver_v_0_0/ts_pt100_AD1_driver_v_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100_AD1_driver_v_0_0 || ORIG_REF_NAME==ts_pt100_AD1_driver_v_0_0}]

# IP: bd/ts_pt100/ip/ts_pt100_fixedPoint_0_0/ts_pt100_fixedPoint_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100_fixedPoint_0_0 || ORIG_REF_NAME==ts_pt100_fixedPoint_0_0}]

# IP: bd/ts_pt100/ip/ts_pt100_package_ext_0_0/ts_pt100_package_ext_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100_package_ext_0_0 || ORIG_REF_NAME==ts_pt100_package_ext_0_0}]

# IP: bd/ts_pt100/ip/ts_pt100_clk_wiz_0_0/ts_pt100_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100_clk_wiz_0_0 || ORIG_REF_NAME==ts_pt100_clk_wiz_0_0}]

# IP: bd/ts_pt100/ip/ts_pt100_clk_box_0_0/ts_pt100_clk_box_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ts_pt100_clk_box_0_0 || ORIG_REF_NAME==ts_pt100_clk_box_0_0}]

# XDC: bd/ts_pt100/ip/ts_pt100_clk_wiz_0_0/ts_pt100_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ts_pt100_clk_wiz_0_0 || ORIG_REF_NAME==ts_pt100_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/ts_pt100/ip/ts_pt100_clk_wiz_0_0/ts_pt100_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ts_pt100_clk_wiz_0_0 || ORIG_REF_NAME==ts_pt100_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/ts_pt100/ip/ts_pt100_clk_wiz_0_0/ts_pt100_clk_wiz_0_0_ooc.xdc

# XDC: bd/ts_pt100/ts_pt100_ooc.xdc
