# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Mods/Arty_Master.xdc

# Block Designs: bd/SDC_CLL/SDC_CLL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL || ORIG_REF_NAME==SDC_CLL}]

# IP: bd/SDC_CLL/ip/SDC_CLL_AD1_driver_v_0_2/SDC_CLL_AD1_driver_v_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_AD1_driver_v_0_2 || ORIG_REF_NAME==SDC_CLL_AD1_driver_v_0_2}]

# IP: bd/SDC_CLL/ip/SDC_CLL_AD1_driver_v_1_0/SDC_CLL_AD1_driver_v_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_AD1_driver_v_1_0 || ORIG_REF_NAME==SDC_CLL_AD1_driver_v_1_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_PWM_0_0/SDC_CLL_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_PWM_0_0 || ORIG_REF_NAME==SDC_CLL_PWM_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_process_v_0_0/SDC_CLL_process_v_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_process_v_0_0 || ORIG_REF_NAME==SDC_CLL_process_v_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_clk_wiz_0_0 || ORIG_REF_NAME==SDC_CLL_clk_wiz_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_clk_box_0_0/SDC_CLL_clk_box_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_clk_box_0_0 || ORIG_REF_NAME==SDC_CLL_clk_box_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_package_ext_0_1/SDC_CLL_package_ext_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_package_ext_0_1 || ORIG_REF_NAME==SDC_CLL_package_ext_0_1}]

# IP: bd/SDC_CLL/ip/SDC_CLL_pre_process_0_0/SDC_CLL_pre_process_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_pre_process_0_0 || ORIG_REF_NAME==SDC_CLL_pre_process_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_AD1_driver_v_2_0/SDC_CLL_AD1_driver_v_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_AD1_driver_v_2_0 || ORIG_REF_NAME==SDC_CLL_AD1_driver_v_2_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_fixedPoint_0_0/SDC_CLL_fixedPoint_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_fixedPoint_0_0 || ORIG_REF_NAME==SDC_CLL_fixedPoint_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_alarm_HT_v_0_0/SDC_CLL_alarm_HT_v_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_alarm_HT_v_0_0 || ORIG_REF_NAME==SDC_CLL_alarm_HT_v_0_0}]

# IP: bd/SDC_CLL/ip/SDC_CLL_AD1_driver_v_1_1/SDC_CLL_AD1_driver_v_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_AD1_driver_v_1_1 || ORIG_REF_NAME==SDC_CLL_AD1_driver_v_1_1}]

# IP: bd/SDC_CLL/ip/SDC_CLL_AD1_driver_v_3_0/SDC_CLL_AD1_driver_v_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDC_CLL_AD1_driver_v_3_0 || ORIG_REF_NAME==SDC_CLL_AD1_driver_v_3_0}]

# XDC: bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDC_CLL_clk_wiz_0_0 || ORIG_REF_NAME==SDC_CLL_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SDC_CLL_clk_wiz_0_0 || ORIG_REF_NAME==SDC_CLL_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0_ooc.xdc

# XDC: bd/SDC_CLL/SDC_CLL_ooc.xdc
