# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.cache/wt [current_project]
set_property parent.project_path C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog {
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/new/div_frecuencias.vh
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/new/baudrate_list.vh
}
add_files C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/SDC_CLL.bd
set_property used_in_implementation false [get_files -all c:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/ip/SDC_CLL_clk_wiz_0_0/SDC_CLL_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/SDC_CLL_ooc.xdc]
set_property is_locked true [get_files C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/SDC_CLL.bd]

read_verilog -library xil_defaultlib -sv {
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/new/AD_driver.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/divisor_f.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/PWM/PWM.srcs/sources_1/new/var_duty_clk.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/negar.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/Vrms_DC_lineal.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/rediv_f.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/modo_pid.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/modo_manual.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/signal_gen_pin.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/div_f_pin.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/pin_tx.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/pin_rx.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/pack_ext.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/m3an.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/lowpass_filter.sv
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/alarm_HT.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/AD1_driver_v.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/PWM/PWM.srcs/sources_1/new/PWM.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/imports/src/qtwosComp.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/imports/src/qdiv.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/imports/src/qmult.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/imports/src/qadd.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/div_v.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/new/process_v.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/clk_box.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/Mod_COM_pines_A/package_ext.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/pre_process.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/fixedPoint.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/bits2temp1.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/new/alarm_HT_v.v
  C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/sources_1/bd/SDC_CLL/hdl/SDC_CLL_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/constrs_1/imports/Mods/Arty_Master.xdc
set_property used_in_implementation false [get_files C:/Users/David/Desktop/Hardware/Cargas/02_09_22/SDC_CLL/SDC_CLL.srcs/constrs_1/imports/Mods/Arty_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top SDC_CLL_wrapper -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef SDC_CLL_wrapper.dcp

catch { report_utilization -file SDC_CLL_wrapper_utilization_synth.rpt -pb SDC_CLL_wrapper_utilization_synth.pb }
