# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/David/Desktop/Radiometro/TRANSM_ACOND/TRANSM_ACOND.cache/wt [current_project]
set_property parent.project_path C:/Users/David/Desktop/Radiometro/TRANSM_ACOND/TRANSM_ACOND.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog {
  C:/Users/David/Desktop/Radiometro/SDC_CLL/SDC_CLL.srcs/sources_1/imports/new/baudrate_list.vh
  C:/Users/David/Desktop/Radiometro/SDC_CLL/SDC_CLL.srcs/sources_1/imports/new/div_frecuencias.vh
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/David/Desktop/Radiometro/TRANSM_ACOND/TRANSM_ACOND.srcs/sources_1/new/signal_gen.sv
  C:/Users/David/Desktop/Radiometro/TRANSM_ACOND/TRANSM_ACOND.srcs/sources_1/new/AD1_drive.sv
  C:/Users/David/Desktop/Radiometro/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/new/divisor_f.sv
  C:/Users/David/Desktop/Radiometro/SDC_CLL/SDC_CLL.srcs/sources_1/imports/Radiometro/UART/UART.srcs/sources_1/new/uart_tx.sv
  C:/Users/David/Desktop/Radiometro/TRANSM_ACOND/TRANSM_ACOND.srcs/sources_1/new/AD1_PV1.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/David/Desktop/xdc-master/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files C:/Users/David/Desktop/xdc-master/Arty-A7-35-Master.xdc]


synth_design -top AD1_PV1 -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef AD1_PV1.dcp

catch { report_utilization -file AD1_PV1_utilization_synth.rpt -pb AD1_PV1_utilization_synth.pb }
