# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/mzvic/CePIA/CARGAS/Vivado/david_code/SDC_CLL/SDC_CLL.srcs/constrs_1/imports/Mods/Arty_Master.xdc

# Block Designs: bd/arch/arch.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch || ORIG_REF_NAME==arch}]

# IP: bd/arch/ip/arch_package_ext_0_0/arch_package_ext_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_package_ext_0_0 || ORIG_REF_NAME==arch_package_ext_0_0}]

# IP: bd/arch/ip/arch_SDC_CLL_AD1_driver_v_0_2_0_0/arch_SDC_CLL_AD1_driver_v_0_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_SDC_CLL_AD1_driver_v_0_2_0_0 || ORIG_REF_NAME==arch_SDC_CLL_AD1_driver_v_0_2_0_0}]

# IP: bd/arch/ip/arch_SDC_CLL_clk_box_0_0_0_0/arch_SDC_CLL_clk_box_0_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_SDC_CLL_clk_box_0_0_0_0 || ORIG_REF_NAME==arch_SDC_CLL_clk_box_0_0_0_0}]

# IP: bd/arch/ip/arch_clk_wiz_0_0/arch_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_clk_wiz_0_0 || ORIG_REF_NAME==arch_clk_wiz_0_0}]

# XDC: bd/arch/ip/arch_clk_wiz_0_0/arch_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==arch_clk_wiz_0_0 || ORIG_REF_NAME==arch_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/arch/ip/arch_clk_wiz_0_0/arch_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==arch_clk_wiz_0_0 || ORIG_REF_NAME==arch_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/arch/ip/arch_clk_wiz_0_0/arch_clk_wiz_0_0_ooc.xdc

# XDC: bd/arch/arch_ooc.xdc
